services:
  - type: web
    name: stegoanalyzer-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://stegoanalyzer-api2.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html